### ISSUE TITLE
Add F5 Key

### ISSUE THREAD

**Issue by skiselev** [skiselev/radio-86rk#7]
Apparently, some Radio-86RK variants had F5. It is not difficult to implement, and should be added in the next revision

**Comment by timtashpulatov** [comment]
Cool work.

What keycaps have you used?

**Comment by skiselev** [comment]
@timtashpulatov I've used DSA profile (this ensures that all keys have similar profile) blank keycaps with the letters printed on a transparent tape using a label printer

**Comment by skiselev** [comment]
F5 key added in Version 1.2
